aplicatie1/urls.py
from django.urls import path
from . import views

app_name = 'home_pag'

urlpatterns = [
    path('', views.home, name='home'),
]

aplicatie2/urls.py
from django.urls import path
from . import views

app_name = 'wallet_pag'

urlpatterns = [
    path('', views.wallet, name='wallet'),
]

coinmarket_api/urls.py
from django.urls import path
from coinmarket_api import views

app_name = 'crypto'

urlpatterns = [
    path('', views.coin, name='coin'),
    path('listare/', views.WalletView.as_view(), name='listare'),
    path('add/', views.WalletCreate.as_view(), name='add'),
    path('<int:pk>/update/', views.Edit_coin.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.del_coin, name='sterge'),



]

les_wallet/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicatie1.urls')),
    path('home/', include('aplicatie1.urls')),
    path('wallet/', include('aplicatie2.urls')),
    path('login/', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', include('login.urls')),
    path('crypto/', include('coinmarket_api.urls')),

]

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register_user/', views.register_user, name='register_user'),
]

aplicatie1/models.py
from django.db import models

# Create your models here.

aplicatie2/models.py
from django.db import models

# Create your models here.

coinmarket_api/models.py
from django.db import models

coin_choices = (
('btc', 'btc'), ('eth', 'eth'), ('usdt', 'usdt'), ('usdc', 'usdc'), ('bnb', 'bnb'), ('ada', 'ada'), ('xrp', 'xrp'),
('busd', 'busd'), ('sol', 'sol'), ('doge', 'doge'), ('dot', 'dot'), ('wbtc', 'wbtc'), ('trx', 'trx'), ('steth', 'steth'),
('eth', 'eth'), ('eth', 'eth'), ('avax', 'avax'), ('dai', 'dai'), ('shib', 'shib'), ('leo', 'leo'), ('cro', 'cro'),
('ltc', 'ltc'), ('matic', 'matic'), ('near', 'near'), ('ftt', 'ftt'), ('xmr', 'xmr'), ('bch', 'bch'), ('xlm', 'xlm'),
('link', 'link'), ('okb', 'okb'), ('etc', 'etc'), ('xcn', 'xcn'), ('atom', 'atom'), ('algo', 'algo'), ('flow', 'flow'),
('uni', 'uni'), ('icp', 'icp'), ('vet', 'vet'), ('hbar', 'hbar'), ('tfuel', 'tfuel'), ('ape', 'ape'), ('egld', 'egld'),
('xtz', 'xtz'), ('kcs', 'kcs'), ('sand', 'sand'), ('axs', 'axs'), ('fil', 'fil'), ('aave', 'aave'), ('mana', 'mana'),
('ceth', 'ceth'), ('eos', 'eos'), ('theta', 'theta'), ('cusdc', 'cusdc'), ('grt', 'grt'), ('hbtc', 'hbtc'), ('klay', 'klay'),
('zec', 'zec'), ('ht', 'ht'), ('dfi', 'dfi'), ('bsv', 'bsv'), ('mkr', 'mkr'), ('btt', 'btt'), ('miota', 'miota'),
('usdp', 'usdp'), ('hnt', 'hnt'), ('xec', 'xec'))


class Wallet(models.Model):
    coin_number = models.CharField(max_length=100)
    coin_type = models.CharField(max_length=100, choices=coin_choices)

    def __str__(self):
        return f' {self.coin_number}, {self.coin_type}'

login/models.py
from django.db import models

# Create your models here.

aplicatie1/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

# Create your views here.

aplicatie2/views.py
from django.shortcuts import render


def wallet(request):
    return render(request, 'wallet.html')

coinmarket_api/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from coinmarket_api.models import Wallet


@login_required
def coin(request):
    apidata = requests.get(
        'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false').json()
    return render(request, 'index.html', {'apidata': apidata})


class WalletView(LoginRequiredMixin, ListView):
    model = Wallet
    template_name = 'index2.html'
    context_object_name = "crypto_list"

    def get_context_data(self, *args, **kwargs):
        data = super(WalletView, self).get_context_data(*args, **kwargs)
        return data


class WalletCreate(LoginRequiredMixin, CreateView):
    model = Wallet
    fields = ['coin_number', 'coin_type']
    template_name = 'index2_form.html'

    def get_success_url(self):
        return reverse('crypto:listare')

@login_required
def del_coin(request, pk):
    moneda = Wallet.objects.filter(id=pk)
    moneda.delete()
    return redirect('crypto:listare')

class Edit_coin(LoginRequiredMixin ,UpdateView):
    model = Wallet
    fields = ['coin_number', 'coin_type']
    template_name = 'index2_form.html'

    def get_success_url(self):
        return reverse('crypto:listare')
#queri
# def suma(request):
#     adunare_coin = Wallet.objects.all().aggregate(Sum())
#     return adunare_coin

login/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def login_first(request):
    return render(request, 'templates/enter.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('crypto:coin')
        else:
            messages.success(request,("There was an error logging in, try again"))
            return redirect('login')

    else:
        return render(request, 'enterv1.html')

def logout_user(request):
    logout(request)
    messages.success(request, "Succes")
    return redirect ('wallet_pag:wallet')

def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Registration Succes !"))
            return redirect('wallet_pag:wallet')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {
       "form": form,
    })

aplicatie2/templates/wallet.html
{% load static %}

<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Metas -->
    <title>Exchange Currency - Responsive HTML5 Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}" />
    <!-- Pogo Slider CSS -->
    <link rel="stylesheet" href="{% static 'website/css/pogo-slider.min.css' %}" />
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'website/css/responsive.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'website/css/custom.css' %}" />

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="inner_page" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

    <!-- LOADER -->
<!--    <div id="preloader">-->
<!--        <div class="loader">-->
<!--            <img src="images/loader.gif" alt="#" />-->
<!--        </div>-->
<!--    </div>-->
    <!-- end loader -->
    <!-- END LOADER -->

    <!-- Start header -->
    <header class="top-header">
        <div class="header_top">
            
            <div class="container">
                <div class="row">
                    <div class="logo_section">
                        <a class="navbar-brand" href="/"><img src="{% static 'website/images/logo5.jpg' %}" alt="image"></a>
                    </div>
<!--                    <div class="site_information">-->
<!--                        <ul>-->
<!--                            <li><a href="mailto:exchang@gmail.com"><img src="images/mail_icon.png" alt="#" />exchang@gmail.com</a></li>-->
<!--                            <li><a href="tel:exchang@gmail.com"><img src="images/phone_icon.png" alt="#" />+7123569847</a></li>-->
<!--                            <li><a class="join_bt" href="#">Join us</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
                </div>
            </div>
        
        </div>
        <div class="header_bottom">
          <div class="container">
            <div class="col-sm-12">
                <div class="menu_orange_section" style="background: #ff880e;">
                   <nav class="navbar header-nav navbar-expand-lg"> 
                     <div class="menu_section">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                    <ul class="navbar-nav">
                        <li><a class="nav-link" href="/">Home</a></li>
                        <li><a class="nav-link" href="/#about">About</a></li>
                        <li><a class="nav-link" href="">Wallet</a></li>
                        <li><a class="nav-link" href="/#services">Services</a></li>
                        <li><a class="nav-link" href="/#news">News</a></li>
                        <li><a class="nav-link" href="/#contact">Contact</a></li>
                        {% if user.is_authenticated %}
                        <li><a class="nav-link" href="/logout">Logout</a></li>
                        {% else %}
                        <li><a class="nav-link" href="/login">Login</a></li>
                        {% endif %}


                    </ul>
                </div>
                     </div>
                 </nav>
                </div>
            </div>
          </div>
        </div>
        
    </header>
    <!-- End header -->

    <!-- Start Banner -->
    <div class="section inner_page_banner">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="banner_title">
                        <h3>LeS Wallet</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Banner -->
    
    <!-- section -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-6 layout_padding">
                    <div class="full paddding_left_15">
                        <div class="heading_main text_align_left">
                           <h2><span class="theme_color">LeS</span> Wallet</h2>
                        </div>
                    </div>
                    <div class="full paddding_left_15">
                        <p>Tracking your portfolio is an important part of managing any investment, but you need a portfolio tracker that does everything you need. This is where LeS Wallet steps in to make your investments that much better.</p>
                    </div>

                    <div class="full paddding_left_15">

                        {% if user.is_authenticated %}
                        <a class="main_bt" href="{% url 'login' %}">Enter</a>
                        {% else %}
                        <a class="main_bt" href="{% url 'login' %}">Login</a>
                        {% endif %}

                    </div>
                    <div class="full paddding_left_15">
                        <a class="main_bt" href="{% url 'register_user' %}">Register</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end section -->
   
    <!-- Start Footer -->
    <footer class="footer-box">
        <div class="container">
            <div class="row">
               <div class="col-md-12 white_fonts">
                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <img class="img-responsive" src="{% static 'website/images/s2.png' %}" alt="#" />
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <h3>Quick Links</h3>
                            </div>
                            <div class="full">
                                <ul class="menu_footer">
                                    <li><a href="/">> Home</a></li>
                                    <li><a href="/#about">> About</a></li>
                                    <li><a href="">> Wallet</a></li>
                                    <li><a href="/#services">> Services</a></li>
                                    <li><a href="/#news">> News</a></li>
                                    <li><a href="/#contact">> Contact</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <div class="footer_blog full white_fonts">
                             <h3>Newsletter</h3>
                             <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
                             <div class="newsletter_form">
                                <form action="index.html">
                                   <input type="email" placeholder="Your Email" name="#" required="">
                                   <button>Submit</button>
                                </form>
                             </div>
                         </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <div class="footer_blog full white_fonts">
                             <h3>Contact us</h3>
                             <ul class="full">
                               <li><img src="{% static 'website/images/i5.png' %}"><span>Bld. Timisoara 101N<br>Bucharest</span></li>
                               <li><img src="{% static 'website/images/i6.png' %}"><span>les-wallet@gmail.com</span></li>
                               <li><img src="{% static 'website/images/i7.png' %}"><span>+40 723159197</span></li>
                             </ul>
                         </div>
                            </div>
                        </div>
					</div>
                </div>
			 </div>
        </div>
    </footer>
    <!-- End Footer -->

    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <p class="crp">© Copyrights 2019 design by html.design</p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" id="scroll-to-top" class="hvr-radial-out"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="js/jquery.min.js"></script>
	<script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.pogo-slider.min.js"></script>
    <script src="js/slider-index.js"></script>
    <script src="js/smoothscroll.js"></script>
    <script src="js/form-validator.min.js"></script>
    <script src="js/contact-form-script.js"></script>
    <script src="js/isotope.min.js"></script>
    <script src="js/images-loded.min.js"></script>
    <script src="js/custom.js"></script>
	
</body>

</html>

coinmarket_api/templates/index.html
{% load static %}
{% block content %}
{% endblock %}
<html lang="en">
  <head>
  	<title>Wallet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="{% static 'table-07/https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
	
	<link rel="stylesheet" href="{% static 'table-07/css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Crypto Market</h2>
					<a class="btn btn-success" href="{% url 'crypto:listare' %}">Access LeS Wallet</a>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="table-wrap">
						<table class="table table-bordered table-dark table-hover">
						  <thead>
						    <tr>
						      <th>#</th>
						      <th>Name</th>
						      <th>Symbol</th>
						      <th>Current Price</th>
						      <th>Market Cap</th>

						    </tr>
						  </thead>
						  <tbody>

						  {% for i in apidata %}

						    <tr>

								<td>{{i.market_cap_rank}}.</td>
								<td>{{i.name}}</td>
								<td>{{i.symbol}}</td>
								<td>{{i.current_price}}$</td>
								<td>{{i.market_cap}}$</td>
							</tr>
						  {% endfor %}
						  </tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'table-07/js/jquery.min.js' %}"></script>
  <script src="{% static 'table-07/js/popper.js' %}"></script>
  <script src="{% static 'table-07/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'table-07/js/main.js' %}"></script>

	</body>
</html>

coinmarket_api/templates/index2.html
{% load static %}
<html lang="en">
<head>

    <title>LeS Wallet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet"
          href="{% static 'table-07/https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'table-07/css/style.css' %}">

</head>
<body>
{% load rates %}
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">LeS Wallet</h2>
            </div>
        </div>
        <a class="btn btn-secondary" href="{% url 'crypto:add' %}">Add Coin</a>
        <div class="row">
            <div class="col-md-12">
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Coins</th>
                            <th>Symbol</th>
                            <th>Value</th>
                            <th>Options</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for x in crypto_list %}

                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ x.coin_number }}</td>
                            <td>{{ x.coin_type }}</td>
                            <td>{{ x.coin_type|rates:x.coin_number }}

                            </td>

                            <td>
                                <a href="{% url 'crypto:sterge' x.id %}" class="btn btn-light">Sterge</a>
                                <a href="{% url 'crypto:modifica' x.id %}" class="btn btn-warning">Modifica</a>

                            </td>


                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'table-07/js/jquery.min.js' %}"></script>
<script src="{% static 'table-07/js/popper.js' %}"></script>
<script src="{% static 'table-07/js/bootstrap.min.js' %}"></script>
<script src="{% static 'table-07/js/main.js' %}"></script>

</body>
</html>

coinmarket_api/templates/index2_form.html
{% load static %}

<html lang="en">
<head>
    <title>Wallet</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet"
          href="{% static 'table-07/https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'table-07/css/style.css' %}">

</head>
<body>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">LeS Wallet</h2>
                <form method="POST">
    {% csrf_token %}
    {% for field in form %}
    {{ field.label }} {{ field }}
    {% endfor %}
    <button type="submit">Save</button>
</form>
            </div>
        </div>

        </div>
    </div>
</section>

<script src="{% static 'table-07/js/jquery.min.js' %}"></script>
<script src="{% static 'table-07/js/popper.js' %}"></script>
<script src="{% static 'table-07/js/bootstrap.min.js' %}"></script>
<script src="{% static 'table-07/js/main.js' %}"></script>

</body>
</html>

coinmarket_api/templates/main.html
{% extends 'index2.html' %}

    <a class="btn btn-success" href="{% url 'crypto:add' %}">Creare wallet</a>

    <table class="table">
        <thead>
            <tr>
                <th>Coin</th>
                <th>Valoare</th>

            </tr>
        </thead>


<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>
https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false

login/templates/enterv1.html
{% load static %}

<form action="" method=POST>
    {% csrf_token %}
    <link rel="stylesheet" href="{% static 'login/login.css' %}"
<div class="mb-3">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <button type="submit">Login</button>
  </div>
</form>
<div class="container">
        {% if messages %}
        {% for messages in messages %}
        {{messages}}
        {% endfor %}
        {% endif %}
    </div>

login/templates/register.html
{% load static %}

<form action="" method=POST>
    {% csrf_token %}
    {{ form }}
    <link rel="stylesheet" href="{% static 'login/login.css' %}">
    <button type="submit">Register</button>

</form>
<div class="container">
        {% if messages %}
        {% for messages in messages %}
        {{messages}}
        {% endfor %}
        {% endif %}
    </div>